### ISSUE TITLE
BUG - Installation of 1.4.0 breaks on latest GitLab Mattermost rollback fails.

### ISSUE THREAD

**Issue by skyscooby** [standup-raven/standup-raven#65]
**Summary**

While not technically a coding bug, a vast slice of Mattermost users are using MM via the version included with the GitLab Omnibus package. Gitlab 12.0 was just released (always on the 22nd of the month) with Mattermost 5.11 included.. but v 1.4.0 of standup-raven requires 5.12.  Thus many users upgrading today will get an error that the plugin requires 5.12. 

You can see the version matrix here: https://docs.gitlab.com/omnibus/gitlab-mattermost/

Also rolling back also fails  (via uploading the old plugin through Management UI pane in the System Console). I am not sure if this is a bug in the Mattermost console,  a "design feature" or something missing in standup-raven plugin's rollback process.

**Expected behavior**
-> Ensure you are testing / supporting back to the MM version included with the latest Gitlab Release.
-> Clearly indicate on the releases page the value of minimum_server_ver to warn users not to upgrade until their server meets your requirements..
-> Possibly open bugs with mattermost as one would think upgrading should be stopped cold if the currently running server version is lower than what is defined in a plugins definition. 

**Observed Behavior**
Upgrading to 1.4.0 results in:
```
2019-06-25_07:02:48.40756 {"level":"error","ts":1561446168.4074988,"caller":"mlog/log.go:172","msg":"Unable to activate plugin","plugin_id":"standup-raven","error":"plugin requires Mattermost 5.12.0: standup-raven"}
```

Rolling back the plugin via the Management UI in System Console lowers the installed version back to 1.3.0 but doesn't lower the min_server_version to the previous value resulting in the same failure after rollback.

**WORKAROUND**
Manually edit /var/opt/gitlab/mattermost/plugins/standup-raven/plugin.json to lower the min_server_version to the version of your server.

**Environment**
-  Mattermost version: e.g. 5.10 - Gitlab 11.11
-  OS: Ubuntu

**Comment by harshilsharma63** [comment]
@skyscooby thanks for the suggestions and the report. There are multiple things here -

> Ensure you are testing / supporting back to the MM version included with the latest Gitlab Release

I completely agree that we should be testing on not only the latest Mattermost but also older, supported versions. I'll need to dig a bit more into Gitlab Omnibus versions. I'm currently not aware about them

> Clearly indicate on the releases page the value of minimum_server_ver to warn users not to upgrade until their server meets your requirements..

I couldn't agree more. Release notes should clearly indicate not only the minimum required Mattermost version, but also the maximum.

> Possibly open bugs with mattermost as one would think upgrading should be stopped cold if the currently running server version is lower than what is defined in a plugins definition.

Well, currently the for updating a plugin you first uninstall the existing one, then upload the new one. I see what you are saying here. Something like a straight upgrade functionality which reverts back if the updated version didn't work. I didn't see this is fully possible a plgin may update resources such as KV store, leaving it in a non-backward compatible state.

> Also rolling back also fails (via uploading the old plugin through Management UI pane in the System Console). I am not sure if this is a bug in the Mattermost console, a "design feature" or something missing in standup-raven plugin's rollback process.

Standup Raven 1.3 won't work in Mattermost v5.12 due to removal of `XMLHttpRequest` in favor of `CSRF` tokens.

**Comment by skyscooby** [comment]
> Well, currently the for updating a plugin you first uninstall the existing one, then upload the new one.

This is not currently enforced by the mattermost management UI.... I upgraded from 1.2.0 -> 1.3.0 just by uploading the new file.

**Comment by harshilsharma63** [comment]
@skyscooby Ah, I wasn't aware of that.

**Comment by harshilsharma63** [comment]
@skyscooby We'll pick your suggestions. I'm closing this issue as I don't see any immediate action to be taken. Feel free to re-open or comment for anything.
